export const SERVER = 'http://localhost:8000/'
export const LOGIN = 'api/v1/rest/login/'
export const CURRENT_USER = 'api/v1/rest/user/'
export const REGISTER = 'api/v1/rest/registration/'
export const LOGOUT = 'api/v1/rest/logout/'
