export const SERVER = 'http://localhost:8000/'
export const TO_LOGIN = 'api/v1/rest/login/'
export const TO_CURRENT_USER = 'api/v1/rest/user/'
export const TO_REGISTER = 'api/v1/rest/registration/'
export const TO_LOGOUT = 'api/v1/rest/logout/'
